### ISSUE TITLE
Latest version on galaxy seems to be 1.6.33

### ISSUE THREAD

**Issue by rrey** [riemers/ansible-gitlab-runner#211]
But your repo has 1.6.35 that contains a fix around tls ca support that I cannot get through Galaxy.

It seems 1.6.34 and 1.6.35 needs to be released.

**Comment by tjaacks** [comment]
This would be interesting for me as well. Will the role on Ansible Galaxy ever be updated again? And if so, when is that gonna happen?

**Comment by hnk** [comment]
@riemers I am also running into this issue. Update of the galaxy repository seems to be failing since 1.6.33 :(

FIY @tjaacks / @rrey :
I did successfully install the role directly from git, using a version constraint, using the methods described in [the ansible documentation](https://galaxy.ansible.com/docs/using/installing.html).

**Comment by riemers** [comment]
I think its ok now, sometime galaxy just doesn't "auto do it"

**Comment by hnk** [comment]
Can confirm that ansible galaxy is up to date now. Thanks for the update!
