### ISSUE TITLE
Fix permissions of gitlab-runner directory

### ISSUE THREAD

**Issue by tjaacks** [riemers/ansible-gitlab-runner#216]
The `ansible-gitlab-runner` rule creates the gitlab-runner directory [with permissions `0755`](https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/register-runner.yml#L10). Whenever I upgrade the `gitlab-runner` package on my system (Ubuntu 20.04), the permissions of this directory change to `0700`. We are periodically checking our machine state by running `ansible-playbook --check` and after each package upgrade the check fails due to this difference.

Is there a specific reason why this role sets the permissions to `0755`? Can this be changed to `0700`?

**Comment by riemers** [comment]
I think this is more dependent on the usage. CIS hardened redhat images have a umask more to the 700 where as default ubuntu/debian installs will not.  So this could also be that your umask is just set more restrictive and the package uses that instead. One could say instead of using 0755 use the umask of the current user. But that would involve some rework. I only maintain the repo on best effort so i usually only merge PR's at the moment. But this is the cause i would say.

**Comment by tjaacks** [comment]
Thanks for your reply. We are using Ubuntu and have not changed our umask. When i run `umask` under my user it says `0002`, which is not restrictive. So I don't see any correlation between the set permissions `0700` and our umask.

Alternative suggestion: only create the `gitlab-runner` dir if it does not exist already. Would you accept a PR for that?

**Comment by riemers** [comment]
PR's are always welcome, if that would help you out sure.

**Comment by tjaacks** [comment]
Great, I will take care of that.
