### ISSUE TITLE
Removed from galaxy

### ISSUE THREAD

**Issue by JD-ISWT** [riemers/ansible-gitlab-runner#290]
Seems that the role is not installable throught galaxy anymore since this morning?

```
[WARNING]: - riemers.gitlab-runner was NOT installed successfully: - sorry, riemers.gitlab-runner was not found on https://galaxy.ansible.com/api/. 
[WARNING]: The requirements file 'requirements.yml' contains collections which will be ignored. To install these collections run 'ansible-galaxy
```

Any info on this?

**Comment by malacration** [comment]
I have the same problem! I verified that the version I was using is not present. However, even after updating to 2.0.3, I still have the problem

**Comment by guenhter** [comment]
https://github.com/riemers/ansible-gitlab-runner/pull/287

https://forum.ansible.com/t/lost-all-history-of-ansible-role-after-delete-of-a-another-role/1753

**Comment by riemers** [comment]
Yeah, also i said don't add the `ansible` in front of it.. but i still got it for free. https://galaxy.ansible.com/ui/standalone/roles/riemers/ansible-gitlab-runner/ its here if you really need it though.

But boy is this one big facepalm.. 

![image](https://github.com/riemers/ansible-gitlab-runner/assets/682041/8e9bc9fd-bd1b-40d3-a8d3-ea87fbf5684c)

Just to show.. --role-name was gitlab-runner. Yet it placed it with ansible in front of it..

**Comment by JD-ISWT** [comment]
I specified the github url as workaround:
```
  - name: riemers.gitlab-runner
    src: "https://github.com/riemers/ansible-gitlab-runner"
    version: "v1.6.50"

```

which one would be the better solution?

**Comment by riemers** [comment]
You can take the role as ansible-gitlab-runner if you want it off galaxy, you get the latest version. But if you want a certain version then take it off github. Since the updates never worked after the galaxy updates i cannot be 100% certain it works. Since at the same time travis also decided to change. Talk about having all in 1 go ;) on a personal level my bike broke down (electric) and my car (electric) also broke down. So its been a fun experience lately. But.. 

https://www.youtube.com/watch?v=dQw4w9WgXcQ 😎

**Comment by riemers** [comment]
Ok that automation is a bit off…
