### ISSUE TITLE
Default branch name

### ISSUE THREAD

**Issue by guenhter** [riemers/ansible-gitlab-runner#300]
Hi,

nowadays (since git 2.28 https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup), the default branch name of repos is usually `main` and not `master` any more. Should this be changed here as well? 

I can imagine to change the default branch but keep the old `master` still alive (and also up to date with `main`) for a certain time as "grace period".

**Comment by guenhter** [comment]
@riemers  any thoughts on that? Will it harm the ansible-galaxy?

**Comment by riemers** [comment]
Have no issues with it
________________________________
Van: Günther Grill ***@***.***>
Verzonden: Tuesday, January 9, 2024 4:11:56 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [riemers/ansible-gitlab-runner] Default branch name (Issue #300)


@riemers<https://github.com/riemers> any thoughts on that? Will it harm the ansible-galaxy?

**Comment by riemers** [comment]
Ow and ansible galaxy is poo 💩;) I honestly don’t know how it works correctly and support is bad. See readme. Feel free to make any changes as needed.
________________________________
Van: Erik-jan Riemers ***@***.***>
Verzonden: Tuesday, January 9, 2024 5:20:29 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>; riemers/ansible-gitlab-runner ***@***.***>
CC: Mention ***@***.***>
Onderwerp: Re: [riemers/ansible-gitlab-runner] Default branch name (Issue #300)

Have no issues with it
________________________________
Van: Günther Grill ***@***.***>
Verzonden: Tuesday, January 9, 2024 4:11:56 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [riemers/ansible-gitlab-runner] Default branch name (Issue #300)


@riemers<https://github.com/riemers> any thoughts on that? Will it harm the ansible-galaxy?

**Comment by Grokzen** [comment]
@riemers To pitch in my 5 cents and experience on this. So not talking about the reasons for doing this, just the engineering side and practical standpoints. When i have attempted or done this or seen this done in other repos, more things got broken that had to be fixed or just caused more pain for everyone involved. Yes tooling today is better to deal with default branch, but in the past tooling was generally hard coded to only have master as the default and very few options to manually override this. This caused integrations and automation to break down in a large scale where forks break and ppl had trouble syncing up repos, scripts, notifications or what not all started to have issues. This ofc has improved over the years, but the core idea still remains. One argument for/against this is that this is correlated to how big and how much used a repo is. Doing it in the linux kernel vs here would be orders of magnitude different headache and outcome.

So what me and ppl i talked to about this over the years is that it is in general not worth it from the engineering standpoint to change an existing repo due to any migration always come with cost and pain points. What is much more worth it if you are inclined to change default branch is to only do it for new repos and not to change anything existing. After some discussions and a few beers :P most ppl agree on this point because in the end, most of us are lazy developers and we in general do not want to cause more work for our self then what is required. And that everyone agrees that use whatever words or reasons you want for new tools/git repos/products or whatnot, most ppl don't care about the naming anyway.

In the end if you want to take on the engineering work to change it, do it, it is not impossible to do. But in the end and my opinion on the matter, you introduce a change for something that don't matter in established repos and something that no-one have talked about for a few years by now. I am neutral in your decision @riemers, just to give you some personal experience on this question. And my experience may vary from everyone elses ofc.

**Comment by guenhter** [comment]
Good point. It is not crucial to do this and there would be bigger fish to fry.
