### ISSUE TITLE
Reactivating Tests: Topic "systemd and docker"

### ISSUE THREAD

**Issue by guenhter** [riemers/ansible-gitlab-runner#310]
This issue is more of getting ideas how to fix certain parts of the tests in order to make them run again.

My current issue is specific to docker and systemd. The gitlab-runner obviously uses systemd on e.g. debian. In a container, it is not very common to have systemd available. Does anyone has experience running (or faking) systemd in a container?

ChatGPT made me aware of this: https://medium.com/@TomaszKlosinski/testing-ansible-role-of-a-systemd-based-service-using-molecule-and-docker-4b3608a10ef0

Looking forward to get your opinions

**Comment by riemers** [comment]
Need to free up some time but the python version change helped fix some issues but not the systemd. Got some credits on Travis again. Although it was extended for a month. Pretty weird. 10k credits but already 3k used? As long as it works ;)
________________________________
Van: Günther Grill ***@***.***>
Verzonden: Tuesday, January 23, 2024 8:11:14 AM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [riemers/ansible-gitlab-runner] Reactivating Tests: Topic "systemd and docker" (Issue #310)


This issue is more of getting ideas how to fix certain parts of the tests in order to make them run again.

My current issue is specific to docker and systemd. The gitlab-runner obviously uses systemd on e.g. debian. In a container, it is not very common to have systemd available. Does anyone has experience running (or faking) systemd in a container?

ChatGPT made me aware of this: ***@***.***/testing-ansible-role-of-a-systemd-based-service-using-molecule-and-docker-4b3608a10ef0

Looking forward to get your opinions
