### ISSUE TITLE
Travis tests do not generate runners-config

### ISSUE THREAD

**Issue by m-bucher** [riemers/ansible-gitlab-runner#81]
It looks to me as if the travis-tests currently do not generated a `config.toml` file that includes the configured runners from the test-vars:
```
TASK [ansible-gitlab-runner : include_tasks] ***********************************

skipping: [localhost] => (item={u'run_untagged': True, u'locked': u'false', u'concurrent_specific': u'0', u'tags': [], u'env_vars': [], u'output_limit': 4096, u'docker_privileged': False, u'state': u'present', u'executor': u'shell', u'docker_image': u'', u'name': u'travis-job-062393db-d09f-40dd-a080-24d8103cafa8'}) 
```
I think it is due to the follwing section, where `[runner]`-config is only created for runners that where already present in `config.toml`.
https://github.com/riemers/ansible-gitlab-runner/blob/dc5ac7e895c50ea07436e5891487af4f04410f45/tasks/config-runner.yml#L18-L25
This is never true for travis, because it always makes a fresh install.

Wouldn't it be better to loop over the `gitlab-runner-runners` variable without a condition?

**Comment by riemers** [comment]
If you have improvements for it, by all means go for it. Only once created just so that there was any form of testing. Since there where so many PR's in the past everything changed. Can hardly see the starting point anymore. (is good, but i might even use it less then other people) but do try to keep it up to date.
